### ISSUE TITLE
Classic controller / Hori Battle pad and Wiimote not working whilst WiiU Pro Controller works.

### ISSUE THREAD

**Issue by Loganicx** [niuus/WiiSXRX#11]
Using WiiFlow v5.4.8. Maybe it's just me, but I cannot get this great emulator working with an appendix (wiimote) and a classic controller, Hori Battle Pad. 

I need to push the reset button on the Wii to get into the emulator menu, then both types of controllers work. 

But, If I boot with only the Wii U Pro controller connected it works all the way. 

Anyone else experience this?

Many thanks for working on this emulator.

**Comment by niuus** [comment]
> Using WiiFlow v5.4.8. Maybe it's just me, but I cannot get this great emulator working with an appendix (wiimote) and a classic controller, Hori Battle Pad.
> 
> I need to push the reset button on the Wii to get into the emulator menu, then both types of controllers work.
> 
> But, If I boot with only the Wii U Pro controller connected it works all the way.
> 
> Anyone else experience this?
> 
> Many thanks for working on this emulator.

Hi. It's a known issue with the Wiiflow implementation. Check here for a workaround:
https://gbatemp.net/threads/wiisx-rx-a-new-fork.570252/page-7#post-9186635
