### ISSUE TITLE
[FEATURE]　Optional automatic save state and load state (kind of like VC on non-N64 games)?

### ISSUE THREAD

**Issue by NintendoManiac64** [niuus/WiiSXRX#13]
The official virtual console on the Wii has the function to automatically save state when quitting and then automatically loading state the next time you load a game (albeit not for N64 games on the Wii, no idea about Wii U)

So how realistic would it be if WiiSX RX had this function?  I mean, it already automatically saves the memory card save data when quitting and/or when powering down the console, so I'm kind of wondering if maybe it wouldn't be to unrealistic for a setting to instead straight up create a save-state when quitting or powering off the console, and then perhaps a second setting to then allow automatic loading of the aforementioned save state?

This would all be optional of course, perhaps even on a per-game basis via a meta.xml argument in-conjunction with autoboot? (that way one could enable it only for specific games since it may be pointless or undesirable for certain other games)

**Comment by niuus** [comment]
**No** feature requests, but pull requests and contributions are encouraged. Submit any changes or improvements and i'll gladly review them.
