### ISSUE TITLE
[FEATURE]　Ability to map one Playstation button to multiple Wii buttons?

### ISSUE THREAD

**Issue by NintendoManiac64** [niuus/WiiSXRX#14]
I noticed that WiiSX RX, like Wii64/Not64, lets you map multiple Playstation buttons to a single Wii button, but does not allow you to map one Playstation button to multiple Wii buttons (something that is common on PC emulators such as Dolphin and the like).

I don't suppose there's any way to be able to do this, e.g. allowing one to map both the B button and Y button to the square button?  I imagine this would be most useful for the shoulder buttons, like for games that only use a single set (e.g. L1 and R1), it'd let you map them to L and R as well as ZL and ZR.

**Comment by niuus** [comment]
**No** feature requests, but pull requests and contributions are encouraged. Submit any changes or improvements and i'll gladly review them.
