### ISSUE TITLE
[FEATURE]　Treat original classic controller and classic controller pro as different controller types with separate button configs?

### ISSUE THREAD

**Issue by NintendoManiac64** [niuus/WiiSXRX#15]
Both Nintendont and Devolution are able to identify the classic controller pro as being different from the original classic controller and therefore provide a different button mapping, so I would think a similar thing would theoretically be possible in WiiSX RX.

I would think that just treating it as a different controller altogether with a separate button mapping, like how the GameCube controller and classic controller have separate button mappings, would be the best way the achieve this.  Ideally it may be a good idea to have a separate controller icon for the CCpro as well, and I'd even be willing to help out on that if needed as I do have some experience in that area.

(the main thing is that I wouldn't want it doing the Nintendont/Devolution method of forcing the swapping of L/R with ZL/ZR on a CCpro since there are some games where I actually don't want that to occur, particularly those in the Bust-A-Move series)

**Comment by niuus** [comment]
**No** feature requests, but pull requests and contributions are encouraged. Submit any changes or improvements and i'll gladly review them.
