### ISSUE TITLE
[FEATURE]　Support .CHD files for game ISOs?

### ISSUE THREAD

**Issue by NintendoManiac64** [niuus/WiiSXRX#16]
The .CHD format was originally created for MAME so that games with multiple files could be stored in a single file, but it's used with some newer PS1 emulators as well since PS1 games can similarly contain a whole slew of .BIN files.

General non-technical info: https://www.maketecheasier.com/what-are-chd-files/

**Comment by niuus** [comment]
It's already in the "Goals" section.

Also, no feature requests, but pull requests and contributions are encouraged.
