### ISSUE TITLE
Player order completely ignores wiimote and/or GC pad player number if controllers or attachments are different

### ISSUE THREAD

**Issue by NintendoManiac64** [niuus/WiiSXRX#18]
If the 1st player wiimote has no attachment connected and the 2nd player wiimote has a nunchuck connected, the 2nd player wiimote will be made 1st player in WiiSX RX.

Similarly, if a gamecube controller is plugged into the 3rd controller port on the wii console while a wiimote with a classic controller is powered on and identifies itself as 1st player with a class, WiiSX RX will make the gamecube controller 1st player and the wiimote + classic controller as second player.

Lastly, if you have two wiimotes where the 1st player wiimote has a nunchuck while the second player wiimote has a classic controller, the 2nd player wiimote + classic controller will be made 1st player in WiiSX RX while the 1st player wiimote + nunchuck will be made 2nd player.

So basically player order is primarily decided as gamecube > classic controller > nunchuck > wiimote by itself, and _then_ only if a controller or attachment is the same will it then go by controller player number.

Is that not all a bit... absurd?  Outside of Wii64/Not64 (which basically uses the same emulator front-end as a foundation), I don't think there's any other wii software, commercial or homebrew, that operates this way.  Is it not much more sensible to just follow the controller player-number as-is like in Nintendont, with the single exception of gamecube controllers taking priority over a wiimote of the same player number (e.g. if you have 2 wiimotes powered on and a gamecube controller in the 2nd port, the 1st player wiimote would be made 1st player in WiiSX RX while the gamecube controller would be made 2nd player while the remaining wiimote would be made 3rd player or, well, an ignored controller since WiiSX RX maxes out at 2 players), again in the same way that Nintendont operates?

**Comment by niuus** [comment]
> Is that not all a bit... absurd? Outside of Wii64/Not64 (which basically uses the same emulator front-end as a foundation), I don't think there's any other wii software, commercial or homebrew, that operates this way.

It isn't. But you can pick and choose your custom order, as there is a specific option for it, same as in Not64/Wii64.

Of course, if you make a pull request with a new improved version, i will gladly test your code and integrate it to the emulator if it suits better.
