### ISSUE TITLE
"Home" button isn't an option for returning to emulator menu when using nunchuck or wiimote by itself despite being an option for classic controllers

### ISSUE THREAD

**Issue by NintendoManiac64** [niuus/WiiSXRX#19]
It would seem that, when using a nunchuck or when using a wiimote by itself, you can't set the "Home" button as the method for returning to the emulator menu when a game is running.

Yet for a classic controller, the "Home" button *is* an option for going back to the emulator menu, so perhaps this was simply an oversight?

**Comment by niuus** [comment]
> It would seem that, when using a nunchuck or when using a wiimote by itself, you can't set the "Home" button as the method for returning to the emulator menu when a game is running.
> 
> Yet for a classic controller, the "Home" button _is_ an option for going back to the emulator menu, so perhaps this was simply an oversight?

There is only so much buttons on a Wiimote, which is still a poor way to play the majority of games. You seem to forget that the PSX _Start_ button is vital in many titles, that's what the Home button is for and that's is why there is a button combo for going back to the menu. Not an oversight.

Check the config and change it to your liking.

**Comment by NintendoManiac64** [comment]
I'm just thinking that there are games like Bust-A-Move 4 that don't even use all of the buttons on a wiimote let alone a wiimote+nunchuck, meaning one can easily play that game with dpad=dpad, x=2, triangle=1, start=plus (and then optionally L1=B and R1=A).

But just for clarification, is this "needing as many buttons as possible" the same reason why, when using the nunchuck, the PSX right analog can only be mapped to tilt and IR and not also the dpad? (mapping analog stock to the wii dpad is something the newest Not64 added)
