### ISSUE TITLE
Colony Wars 3 - Red sun NOT Working

### ISSUE THREAD

**Issue by qamichele59** [niuus/WiiSXRX#21]
It Couldn't get past the BIOS screen, then always i greeted me a code dump dsi exception error any to fix for this? How about tried it work on PCSX-Reloaded Emu on my PC

**Comment by qamichele59** [comment]
It has been a error keeps coming out on wiisxrx but will not work on libretro3ds PCSXrearmed on my Sanrio new 3ds My Melody console.

**Comment by newestdodain47** [comment]
Does this game work with Interpreter? How about work perfect on pc using PCSX-Reloaded?

**Comment by newestdodain47** [comment]
> It has been a error keeps coming out on wiisxrx but will not work on libretro3ds PCSXrearmed on my Sanrio new 3ds My Melody console.

Say it works fine on PCSXRearmed libretro3ds core on Sanrio New3DS Console ;)
