### ISSUE TITLE
Star Wars - Episode I - Jedi Power Battles NOT WORKING on WiiSXRX? PLS Help!

### ISSUE THREAD

**Issue by qamichele59** [niuus/WiiSXRX#26]
I won't get past the BIOS Screen, then always i greeted me a black screen with much noise any to fix for this? They all work on PCSX-Redux Emulator on my PC.

**Comment by newestdodain47** [comment]
Does this game work with Interpreter? How about to work perfect on pc using pcsx-reloaded?

**Comment by qamichele59** [comment]
> Does this game work with Interpreter? How about to work perfect on pc using pcsx-reloaded?

Interpreter produces sound issues and freezing, but not working on PCSXRearmed libretro3ds core on Sanrio New3DS Console :(

**Comment by newestdodain47** [comment]
> > Does this game work with Interpreter? How about to work perfect on pc using pcsx-reloaded?
> 
> Interpreter produces sound issues and freezing, but not working on PCSXRearmed libretro3ds core on Sanrio New3DS Console :(

Say it works fine on PCSXRearmed libretro3ds core on Sanrio New3DS Console ;)
