### ISSUE TITLE
Support v-sync and USB gampepad (HID)

### ISSUE THREAD

**Issue by spielvan** [niuus/WiiSXRX#3]
Hello my friend Niuus, first of all my congratulations for the wonderful work you have done, WIISRX is fantastic, and I would ask if it would be possible to put support for v-sync, USB (HID) and HD on NTFS? a hug and success always.

**Comment by NintendoManiac64** [comment]
I'd think the main benefit for USB gamepads would be the ability to use PS3 and newer PlayStation controllers.

Though it may be worth noting that wired Xbox 360 controllers have also been supported by other Wii homebrew emulators like Snes9X GX, but that's obviously not HID-based.

On the subject of non-HID USB controllers, there's of course also the official 1st party GameCube USB adapter which is supported by the likes of Nintendont.

**Comment by niuus** [comment]
> Hello my friend Niuus, first of all my congratulations for the wonderful work you have done, WIISRX is fantastic, and I would ask if it would be possible to put support for v-sync, USB (HID) and HD on NTFS? a hug and success always.

V-Sync is now supported in version 2.6.
