### ISSUE TITLE
Xenogears memory card unplayable......is so crappy on WiiSXRX? PLS HELP!

### ISSUE THREAD

**Issue by qamichele59** [niuus/WiiSXRX#30]
I actually starts the game, then it always i greeted me crashing when trying to access the memory card file, so any to fix this?

**Comment by newestdodain47** [comment]
Test this on my PC with a PCSX-Reloaded and still reporting back if it works here with X86 interpreter and dynarec cores

**Comment by qamichele59** [comment]
> Test this on my PC with a PCSX-Reloaded and still reporting back if it works here with X86 interpreter and dynarec cores

dom't work with a X86 Interpreter and dynarec cores on PCSX-Reloaded :-/
