### ISSUE TITLE
(Bug, GFX) Driver 2 US, Driver 2 DEMO games are causing crash on WiiSXRX(?) please heeellpp!

### ISSUE THREAD

**Issue by qamichele59** [niuus/WiiSXRX#31]
Just sound, no graphics or image, and buttons seem to unresponsive and screen is totally black and fps counter stops rendering graphics and picture too, so any to fix this? I got verificated by this BIN/ISO File using PCSX-Revolution r84(?) Emulator, everything plays well to load the FMVs but is so very slow to play. Now are all work on DuckStation on my PC.

**Comment by qamichele59** [comment]
Has been totally distorted sounds and screen transformed black and is very much crappy on the WiiSX but will **NOT** work on PCSX-ReARMed libretro3DS on my New3DS Sanrio Console, just causing a "data abort" when starting the first mission of undercover mode.

**Comment by newestdodain47** [comment]
Does this game work with HLE BIOS? How about pn pc using pcsx-reloaded?

**Comment by newestdodain47** [comment]
> Has been totally distorted sounds and screen transformed black and is very much crappy on the WiiSX but will **NOT** work on PCSX-ReARMed libretro3DS on my New3DS Sanrio Console, just causing a arm11 "prefetch abort (kernel panic)" exception occurred when starting the first mission of undercover mode.

Everything it works on PCSX-ReARMed libretro3DS on my New3DS Sanrio Console, but it finished the 1st mission from the undefcover mode :)
