### ISSUE TITLE
Issue with Driver 2 on WiiSXRX? PLS help!

### ISSUE THREAD

**Issue by qamichele59** [niuus/WiiSXRX#32]
I just have an issue with the game "Driver 2". When the game starts and the intro video starts, you can only hear the audio of the video but the screen is totally black (FPS Counter freezes too). All buttons seem unresponsive too, so there is no way to skip the video nor to proceed or do anything. I got verificated by bin using PCSX-Revolution r84(?) Emulator, everything plays well to load the fmvs but is very slow. They all work on Duckstation on my PC, and finished the first mission of the undercover mode.

**Comment by qamichele59** [comment]
Impossibly because a copyprotection error by reflections interactive and infogrames on WiiSXRX, but has ARM11 **KERNEL PANIC** exception occurred after Is Loading Message Screen on Pcsx-Rearmed 3ds libretro core.

**Comment by newestdodain47** [comment]
Does have this game work with HLE BIOS? How about work perfect on my PC using PCSX-Reloaded?
