### ISSUE TITLE
megaman legends 2 crashed after capcom screen??

### ISSUE THREAD

**Issue by qamichele59** [niuus/WiiSXRX#34]
Still starts the game but can not get past the capcom logo then still keeps crashing with garbled noise any to fix for this?

**Comment by newestdodain47** [comment]
Test this on my PC with a PCSX-Reloaded and report back if it works there with X86 Interpreter and Dynarec Cores.

**Comment by qamichele59** [comment]
> Test this on my PC with a PCSX-Reloaded and report back if it works there with X86 Interpreter and Dynarec Cores.

not work with a X86 Interpreter and Dynarec Cores on a PCSX-Reloaded :/
