### ISSUE TITLE
Tony Hawks Pro Skater crashes

### ISSUE THREAD

**Issue by qamichele59** [niuus/WiiSXRX#35]
it doesn't get past the BIOS screen then always i greeted me a black screen any to fix for this? Now all work on DuckStation emulator.

**Comment by newestdodain47** [comment]
Does this game work with HLE BIOS? How about on PC using pcsx-reloaded?

**Comment by qamichele59** [comment]
> Does this game work with HLE BIOS? How about on PC using pcsx-reloaded?

HLE BIOS Produces random sounds and freezing.

**Comment by qamichele59** [comment]
Still keeps breaking on wiisxrx/wiisx emulators but has been a "KERNEL PANIC" exception occurred after title screen and not work anymore on PCSXRearmed libretro3ds core on Sanrio New3DS Console ;(

**Comment by newestdodain47** [comment]
> Still keeps breaking on wiisxrx/wiisx emulators but has been a "KERNEL PANIC" exception occurred after title screen and not work anymore on PCSXRearmed libretro3ds core on Sanrio New3DS Console ;(

Say it works on PCSXRearmed libretro3ds core on Sanrio New3DS Console ;)
