### ISSUE TITLE
Tony Hawks Pro Skater 4, Tony Hawks Pro Skater 3 are causing crash on WiiSXRX????????

### ISSUE THREAD

**Issue by qamichele59** [niuus/WiiSXRX#36]
Just sound, unsupported graphics or black screens and freezing, all buttons doesn't respond, so any to fix this?

**Comment by newestdodain47** [comment]
Does this game work with interpreter? How about work perfect on PC using PCSX-Reloaded?

**Comment by qamichele59** [comment]
> Does this game work with interpreter? How about work perfect on PC using PCSX-Reloaded?

Interpreter produces sound issues and crashing but not working on PCSXRearmed libretro3ds core on Sanrio New3DS Console :(......

**Comment by newestdodain47** [comment]
> > Does this game work with interpreter? How about work perfect on PC using PCSX-Reloaded?
> 
> Interpreter produces sound issues and crashing but not working on PCSXRearmed libretro3ds core on Sanrio New3DS Console :(......

Say it works fine on PCSXRearmed libretro3ds core on Sanrio New3DS Console ;)
