### ISSUE TITLE
wiisxrx 2.5

### ISSUE THREAD

**Issue by matto21** [niuus/WiiSXRX#55]
@niuus 
wiisxrx 2.5 starting the game from wiiflow lite does not recognize the classic controller and only recognizes the wiimote and I cannot save the configuration for the classic controller, I have everything on Hard Disk
The emulator as it is is fine, but it is very troublesome to reconfigure it again every time I want to play.
It is possible to have the classic controller recognized when starting games via wiiflow lite

Thank you.

**Comment by niuus** [comment]
After opening the game, enter the emulator Menu and unplug-replug the controller. It will work fine. Known bug with Wiiflow only..

After that, map your preferences and save the config to your used media.
