### ISSUE TITLE
gameid from previous when loading another game

### ISSUE THREAD

**Issue by eku** [niuus/WiiSXRX#56]
According to [this thread](https://gbatemp.net/threads/wiisx-gameshark-v5.300994/), `WiiSX/WiiSX RX` doesn't clear the old gameid before loading a new game. So this makes the usage of `Gameshark v5` tricky.

Could you please have a look at this and fix it. Thanks in advance.

**Comment by niuus** [comment]
I'll add this to a documented bug report list.

**Comment by eku** [comment]
> I'll add this to a documented bug report list.

What does it mean? No fixable or what?
