### ISSUE TITLE
No CDDA or Multi-track support; Causes crash in Vib-Ribbon

### ISSUE THREAD

**Issue by GeigerCounter** [niuus/WiiSXRX#6]
As the title says, due to CDDA audio being force-disabled and there being seemingly no way to handle multi-track disks games that require them will crash. I noticed this in Vib-Ribbon, which absolutely doesn't work without it since the game's schtick is that it is dynamically generated based on the CD audio and can even support hot-swapping disks to whatever CD you'd like. While I would like the latter, at very least the former is a critical bug that renders the game unplayable.

**Comment by newestdodain47** [comment]
Test this one on PC with a PCSX-Reloaded and still reporting back if it works here with the X86 Interpreter and Dynarec Cores.

**Comment by newestdodain475** [comment]
Does have this will work with HLE? How about on my PC using PCSX-Reloaded?

**Comment by michele559** [comment]
Does this work with interpreter and hle bios? How about to play on PC using pcsx-reloaded?

**Comment by michele5943** [comment]
When getting to work on PSX2PSP EBOOT after trying to convert the game into a eboot.pbp with Simple Popstation GUI on PSP Console 6.60 from year 2005, teh game still crashing in both WiiSXRX and PCSX-Revolution Emulators, but probably the PCSX-ReARMed libretro 3ds core emulator has "prefetch abort (svcBreak)" error screens and the game still doesn't even work on the latest Retroarch3DS PCSX-ReARMed libretro3ds core version.

**Comment by niuus** [comment]
As stated in the readme, pull requests for fixes are always welcome. Otherwise, I can only review it when I have the motivation and the time.
