### ISSUE TITLE
Support subdirectories in smbsharename path

### ISSUE THREAD

**Issue by ryliejamesthomas** [niuus/WiiSXRX#60]
When setting up I kept getting the error message 'SMB failed to load' when trying to load ISOs over SMB.

Tried lots of things, and eventually found the problem was that it didn't like the path in `smbsharename`

My games are a few directories deep on my NAS (`Media\Games\Platform\Sony PlayStation`), and I don't think this is unusual, it'd be nice if it was supported. Changing to `smbsharename = "Media"` works fine though, I just have to dig through stuff to get to my games.

Also it'd be nice if there was a log file to make diagnosing things like this easier, or more useful error messages.

**Comment by niuus** [comment]
Hopefully someone with interest in SMB can make a pull request to the project to fix your issue. I'll add this to a documented bug report list.
