### ISSUE TITLE
WiiSXRX is broken help ;(

### ISSUE THREAD

**Issue by f4arm4** [niuus/WiiSXRX#64]
I have only tested all games so far, but ace combat 3 audio lag and stutters while playing, and worms minor slowdown when the application was in a wii family editon, and when tested in a wii u, the games are made up of repeating loops in every psx game, but the cotm audio lag is gone, I just updated to the latest version of wiiflow

**Comment by f4arm4** [comment]
Testing in my Wii family edition Collection i found
Resident evil 2-3, spider-man (US+JP), destruction derby, need for speed V-rally, and tony hawks pro skater only boot into a blue screen
Final Fantasy IV has audio warping
Final Fantasy IX, and V-Rally (JP) crash the system
V-Rally 2 has some slowdowns and audio crackling in all fmvs
Tales of destiny 1 crashes the system during introduction screen
Worms worldparty (US) has some slowdowns in all modes
Megaman legends 2 (US+EU) crashes the system after capcom screen
Xenogears crashes the system after saving the memcard
street fighter alpha has some slowdowns in some and audio stuttering in the intro
Driver 2 seem to trigger some kind of infogrames piracy protection lock out

**Comment by niuus** [comment]
From the readme:

> **DISCLAIMER: Please do not report issues with specific games, as they may or not be fixed with updates to the code later in the future.**

Also, no reports about issues with Wiiflow, as this is not affiliated.
