### ISSUE TITLE
Force 4:3 Mode [REDUNDANT]

### ISSUE THREAD

**Issue by devlman127** [niuus/WiiSXRX#65]
Running this off Wii U inject and even using the 4:3 mode in the emulator settings still doesn't change the aspect ratio. It's a hassle to manually change my Wii U's aspect ratio every time when I'm never going to play a playstayion game stretched, so can there be a mode to force games to output at 4:3 with black bars or is that not possible?
EDIT: Reading the documentation, Turns out "Force 16:9 Mode" does just that, instead of stretching it to 16:9 like I'm experiencing. Confusing, huh?

**Comment by niuus** [comment]
Not an issue. Closing.
