### ISSUE TITLE
Suport CDDA

### ISSUE THREAD

**Issue by spielvan** [niuus/WiiSXRX#68]
Congratulations bro for the last version, the v-sync was perfect, I believe that now the only thing missing is CDDA support and for XBox 360 control by usb, I was even going to tell you something I have the 8bitdo retro receiver of the mini nes and it doesn't nintendont with support for xbox 360 controller, then i can use the ps3 controller wirelessly with the retro receiver connected to the usb of the wii.

**Comment by spielvan** [comment]
I tried to use this retro receiver on the Snes9x rx latest version, to use the wireless ps3 controller on it, but the snes9x rx did not recognize the receiver, even though it was in x-input.

**Comment by saulfabregwiivc** [comment]
CDDA support is still very experimental (but still not on official WiiSXRX), and it's currently being worked by user @xjsxjs197 in his fork of WiiSXRX: https://github.com/xjsxjs197/WiiSXRX_2022

About the Xbox 360 controller and adapter, as niuus stated, please donate him an Xbox 360 controller and a Retro Receiver for X360 (if you can of course) and he will check.

**Comment by spielvan** [comment]
> CDDA support is still very experimental (but still not on official WiiSXRX), and it's currently being worked by user @xjsxjs197 in his fork of WiiSXRX: https://github.com/xjsxjs197/WiiSXRX_2022
> 
> About the Xbox 360 controller and adapter, as niuus stated, please donate him an Xbox 360 controller and a Retro Receiver for X360 (if you can of course) and he will check.

thanks for your attention, as for the CDDA I have been following this other project, I even have both projects on my sdcard on the Wii and from what I could observe so far, each one has its qualities, as for the control and the retro receiver is difficult because I am unemployed living with their parents, but two better ones saw for sure the important thing is to be healthy

**Comment by eku** [comment]
> CDDA support is still very experimental (but still not on official WiiSXRX), and it's currently being worked by user @xjsxjs197 in his fork of WiiSXRX

@niuus & @xjsxjs197  I would like to see the developers join forces in one project.
