### ISSUE TITLE
WiiSXRX v3.0 and v3.1 code dump error

### ISSUE THREAD

**Issue by gamecubefan1990** [niuus/WiiSXRX#72]
Hello

On WiiSXRX v3.0 is a GUI crash.
If i load the emulator, then press "Quit" and then "OK" without loading a game, it causes an instant DSI code dump error.
On WiiSXRX v2.7 there is no GUI crash.

**Comment by saulfabregwiivc** [comment]
I have made a PR https://github.com/niuus/WiiSXRX/pull/73 for try to fix these issues.
If it doesn't work, of if does partially work, I could check.

**Comment by cuteoreo** [comment]
i had the same problem when try to load a game on my wii.
it doesn't show the .bin file when trying to load the game only the .cue file is shown on the menu

**Comment by gamecubefan1990** [comment]
The code dump error still exists in the new Version 3.1.
When you load the emulator, then press "Quit" and then "OK" without loading a game, it still crash

**Comment by saulfabregwiivc** [comment]
i will check some code of @niuus' WiiSX-RX and @xjsxjs197's WiiStation for find a possible fix for this.

**Comment by saulfabregwiivc** [comment]
@gamecube007 @cuteoreo

@niuus have posted a new build of WiiSXRX 3.1 with a hotfix that apparently fixes the DSI crashes on GUI.
https://github.com/niuus/WiiSXRX/releases

Please redownload WiiSXRX 3.1 and retest, thanks ;)
