### ISSUE TITLE
WiiSXRX 3.1 crashes when launching any game

### ISSUE THREAD

**Issue by BlackPaladin2022** [niuus/WiiSXRX#76]
I didn’t have these issues with earlier versions of the emulator.  (I’ve used 2.5 and 2.7 with no issues.)

Every time I launch any ISO in the emulator, I would get a “Exception (DSI) occurred!” message.  I have to press my reset button to return to the home brew channel.

my Wii’s firmware is at 4.3, and it was softmodded by Letterbomb if that helps.

Here’s a snapshot of the emulator’s crash screen on my TV.

![EB99B1DA-CF47-4370-B9EC-22EEDCCEC2FA](https://user-images.githubusercontent.com/99116758/196711935-37b16d40-e2c2-4282-b64a-903cd259b532.jpeg)

**Comment by saulfabregwiivc** [comment]
are you using HLE or official BIOS (SCPH1001.bin)?

**Comment by BlackPaladin2022** [comment]
> are you using HLE or official BIOS (SCPH1001.bin)?

I used the official BIOS with the emulator, not HLE.

**Comment by BlackPaladin2022** [comment]
Okay, now I feel like a fool.  I checked the settings of the emulator, and the BIOS was set to HLE.  (Last time I had checked, was set to SD… where the BIOS is located.). The emulator works now.

I apologize for any inconvenience.

**Comment by carnage702** [comment]
> Okay, now I feel like a fool. I checked the settings of the emulator, and the BIOS was set to HLE. (Last time I had checked, was set to SD… where the BIOS is located.). The emulator works now.
> 
> I apologize for any inconvenience.

when you update version the bios goes back to hle.
