### ISSUE TITLE
exception dsi occurred

### ISSUE THREAD

**Issue by zetallic** [niuus/WiiSXRX#77]
I installed a spyro rom and put it in my isos folder and unziped it. I have the SCPH1001 bin file.  I put the SCPH1001 bin file into my bios folder. I put the sd card back into my wii and launch wiisxrx. I click the rom that I justed put into the isos folder but it crashes.

Any way to fix this issue?

I am using the lasted version of wiisxrx as I just started modding my wii.

**Comment by carnage702** [comment]
Are you sure you activated the bios? It's not just having it on SD card, you need to go to settings, click bios  and choose SD, then click boot through bios to  yes and then save settings to SD.

**Comment by zetallic** [comment]
I'll try that right now.

**Comment by zetallic** [comment]
Thank you so much for the help! It worked!

**Comment by niuus** [comment]
> I installed a spyro rom and put it in my isos folder and unziped it. I have the SCPH1001 bin file. I put the SCPH1001 bin file into my bios folder. I put the sd card back into my wii and launch wiisxrx. I click the rom that I justed put into the isos folder but it crashes.
> 
> Any way to fix this issue?
> 
> I am using the lasted version of wiisxrx as I just started modding my wii.

Already told you in the forums to check the README and USE the BIOS.
