### ISSUE TITLE
Timing autoFix (Parasite Eve 2, Vandal Hearts) broken on WiiSXRX 3.2 (3.0 and 3.1 works)

### ISSUE THREAD

**Issue by saulfabregwiivc** [niuus/WiiSXRX#78]
Hey there @niuus,

Thanks for your work with WiiSXRX.

A critical bug report: the timing autoFix function (which fixes Parasite Eve 2, Vandal Hearts) on 3.2 now it's broken on all builds (3.0 and 3.1 work though).

Can you see in the code what's going on and in what modification actually break the timing autoFix?

You know, i'm currently making some modifications for add more autoFixes, and tidy up the timing autoFix (all from @xjsxjs197's repo), for later send you a PM for 3.3, but I couldn't get the timing autoFix working due of being broken since 3.2.

Can you check this please? Thanks!!!

@saulfabregwiivc

**Comment by niuus** [comment]
> Hey there @niuus,
> 
> Thanks for your work with WiiSXRX.
> 
> A critical bug report: the timing autoFix function (which fixes Parasite Eve 2, Vandal Hearts) on 3.2 now it's broken on all builds (3.0 and 3.1 work though).
> 
> Can you see in the code what's going on and in what modification actually break the timing autoFix?
> 
> You know, i'm currently making some modifications for add more autoFixes, and tidy up the timing autoFix (all from @xjsxjs197's repo), for later send you a PM for 3.3, but I couldn't get the timing autoFix working due of being broken since 3.2.
> 
> Can you check this please? Thanks!!!

Yep, I had to take the manual fix out temporarily as it clashed with the GTE updates on compilation. That's why I mentioned in the [forums](https://gbatemp.net/threads/wiisxrx_2022-another-fork-of-wiisxrx-released.614405/post-9978141) that if you want to do a PR and make it work, i'll integrate it. I really want to spend some time doing the finishing touches to get NeoCDRX out before 2023, as I have some versions ready.

**Comment by saulfabregwiivc** [comment]
Okay, i think i spotted the problem.

This problem doesn't just happen on WiiSXRX, it's being broken also on WiiStation, in the commit https://github.com/xjsxjs197/WiiSXRX_2022/commit/0f1eb8237012a19ea3ee237066c8ea25638a20f4.

I've opened an issue of this critical bug here too: https://github.com/xjsxjs197/WiiSXRX_2022/issues/48

When xjsxjs197 fixes said bug, i will integrate the fix to my PR i'm currently doing.

EDIT: @niuus , sorry for being just stupid and didn't check the WiiStation repo first for confirm said problem.

**Comment by saulfabregwiivc** [comment]
Closing issue, this was fixed on WiiStation as of commit https://github.com/xjsxjs197/WiiSXRX_2022/commit/d5df2fbc2f2799b351862ae496c26e29a1e66da0

I've opened a PR which fixes said issue on WiiSXRX ;) https://github.com/niuus/WiiSXRX/pull/79
