### ISSUE TITLE
the emulator does not want to open the games

### ISSUE THREAD

**Issue by Lucas73816748816** [niuus/WiiSXRX#81]
in this update if i try to open any game the emulator crashes... i saw if it was only with one game... and it is with any game that i open...

**Comment by saulfabregwiivc** [comment]
did you read the readme? The readme states that better use the official PSX BIOS and not the HLE BIOS...

**Comment by niuus** [comment]
Not a real issue. Closing.

**Comment by Lucas73816748816** [comment]
I already tried to use it... but the emulator crashed anyway

Em sex., 11 de nov. de 2022 11:14, niuus ***@***.***>
escreveu:

**Comment by carnage702** [comment]
> 

that is because your not setting the file correctly, are you putting the bios correctly? do not forget to activate the  bios on the settings after, and if the games dont open maybe your not setting them correctly like bad cue files and such.

**Comment by Lucas73816748816** [comment]
Ok... apparently it was the bios I downloaded that wasn't working... sorry
for the inconvenience...

Em sex., 11 de nov. de 2022 14:47, pedro702 ***@***.***>
escreveu:
