### ISSUE TITLE
[FEATURE] Add sd2sp2 support for GCN

### ISSUE THREAD

**Issue by slash0042** [niuus/WiiSXRX#9]
I would send a PR myself but I'm not that experienced with GC/Wii homebrew and seems that it is a pita to setup the toolchain for certain homebrews (i.e. custom dkppc installations), but here is a example, seems trivial to implement. Thanks in advance and good work on your fork!

https://github.com/extremscorner/not64/commit/8be842aa43927681773c7194bc70064f95ba0177#diff-33b02f762572796b0cc8c9fa55eaa4818d7fb4514f2ef6d3c3e0ab73f423742d

**Comment by niuus** [comment]
I might be interested to implement it in the future. Pull requests are always welcome to speed up the process, of course.
